### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 57600
image_min_pixels: 57600
video_max_pixels: 57600
video_min_pixels: 57600
video_fps: 0.5
video_maxlen: 150
trust_remote_code: true
enable_liger_kernel: true
flash_attn: fa2
use_fast_img_processor: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false  # choices: [true, false]
freeze_multi_modal_projector: false  # choices: [true, false]
freeze_language_model: false  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]


### dataset
dataset: event_inserted_captions_time_unit_second_600k_one_dec_seconds_cleaned_top_wc_top_20.0_percent_images
template: qwen2_vl
cutoff_len: 32768
overwrite_cache: true # load_from_cache_file from HF datasets: false
preprocessing_num_workers: 16
dataloader_num_workers: 4
dataloader_prefetch_factor: 4 # try to use it, supported by HF trainer
dataset_dir: data
media_dir: data
add_timestamp: true
data_video_fps: 0.5 # set 0.5 fps for now to avoid max output length

### output
output_dir: output/event_vlm_dvc_event_inserted_captions_time_unit_second_600k_one_dec_seconds_cleaned_top_wc_top_20.0_percent_images_3B_0.5fps
logging_steps: 1
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null



report_to: wandb
run_name: event_vlm_dvc_event_inserted_captions_time_unit_second_600k_one_dec_seconds_cleaned_top_wc_top_20.0_percent_images_3B_0.5fps

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
